### ISSUE TITLE
Visual Studio Build

### ISSUE THREAD

**Issue by brstv** [libyal/libfsrefs#1]
The build for Visual Studio 2013 seems to be broken. Several file paths might be wrong.

**Comment by joachimmetz** [comment]
The project does not ship 2013 VS files and VS 2008 and 2010 support seem to work:
https://ci.appveyor.com/project/joachimmetz/libfsrefs

So you'll have to provide me with more detail here.

**Comment by joachimmetz** [comment]
> The source distribution package download link seems to be broken. Please fix this

wiki updates, however project does not provide distribution packages. 

per [README](https://github.com/libyal/libfsrefs/blob/master/README)
```

Note that this project currently only focuses on the analysis of the format.

Project information:
* Status: experimental
```

Closing issue, seeing this is work in progress.
