### ISSUE TITLE
Documentation link in the wiki is dead

### ISSUE THREAD

**Issue by aaptel** [libyal/libfsrefs#2]
https://github.com/libyal/libfsrefs/wiki
-> Documentation 
-> https://googledrive.com/host/0B3fBvzttpiiSSmwxUWxManBEMG8/
-> 404

**Comment by joachimmetz** [comment]
Let's bury it in peace then ;) I'll have a look as soon as time permits 

in the mean time documentation was moved here: https://github.com/libyal/libfsrefs/tree/master/documentation

**Comment by joachimmetz** [comment]
wiki updated
