### ISSUE TITLE
there is several error while using visual studio 2015

### ISSUE THREAD

**Issue by aswathyrajalekha** [libyal/libfsrefs#3]

**Comment by joachimmetz** [comment]
thanks for that feedback but without detailed information it will be impossible for me to do anything about it.

**Comment by aswathyrajalekha** [comment]
sln file is not listing the forms properly 
![vc](https://cloud.githubusercontent.com/assets/14839508/25369293/6f72bb28-29a0-11e7-9957-79404a35246c.png)
 on opening

**Comment by aswathyrajalekha** [comment]
Have you done any file recovery in ReFs

**Comment by joachimmetz** [comment]
> Have you done any file recovery in ReFs

Per https://github.com/libyal/libfsrefs/blob/master/README this project is experimental

Follow the build instructions: https://github.com/libyal/libfsrefs/wiki/Building#read-first
This should solve the issues you see in VS2015

**Comment by aswathyrajalekha** [comment]
errors in the above pictures are the error i encountered while importing the solution file.
I am doing a project on Refs so i wanted to know that if you have done any file recovery work on ReFS.

**Comment by joachimmetz** [comment]
> errors in the above pictures are the error i encountered while importing the solution file.

Yes, per https://github.com/libyal/libfsrefs/wiki/Building#read-first you should use a "source distribution package", not the version directly from git.

**Comment by joachimmetz** [comment]
> I am doing a project on Refs so i wanted to know that if you have done any file recovery work on ReFS.

I had no need for doing so, so far.

**Comment by kumartvm** [comment]
The source distribution package download link seems to be broken. Please fix this

**Comment by joachimmetz** [comment]
> The source distribution package download link seems to be broken. Please fix this

wiki updates, however project does not provide distribution packages. 

per [README](https://github.com/libyal/libfsrefs/blob/master/README)
```

Note that this project currently only focuses on the analysis of the format.

Project information:
* Status: experimental
```

Closing issue, seeing this is work in progress.
