### ISSUE TITLE
Update documentation with format version 

### ISSUE THREAD

**Issue by cugu** [libyal/libfsrefs#7]
Offset 40 in the volume header seems to contain the ReFS version (https://github.com/libyal/libfsrefs/blob/master/libfsrefs/fsrefs_volume_header.h#L86)

**Comment by joachimmetz** [comment]
Thx for the report I'll have a look as soon as time permits.

**Comment by joachimmetz** [comment]
Added in https://github.com/libyal/libfsrefs/commit/4817b4bd3be797dd0206c9c2dfa41f68cbb5f04a
